@startuml
    class Personnel {
        id_personnel
        nom
        prenom
        email
        telephone
        diplome
        permis_bateau
    }

    class GarçonDePlage extends Personnel {
    }

    class Moniteur extends Personnel {
    }

    class Proprietaire extends Personnel {
    }

    class Saison {
        id_saison
        date_debut
        date_fin
    }

    class HistSaison {
        id_hist_saison
        date_debut
        date_fin
    }

    class Client {
        id_client
        nom
        prenom
        email
        telephone
        piece_identite
    }

    class Materiel {
        id_materiel
        type_materiel
        caracteristiques
        etat
        date_acquisition
        numero_serie
    }

    class Forfait {
        id_forfait
        type_forfait
        prix
        date_achat
        date_expiration
        seances_restantes
    }

    class Partenaire {
        id_partenaire
        nom
        adresse
        email
        telephone
        type_partenaire
    }

    class HistPartenaire {
        id_hist_partenaire
        nom
        adresse
        email
        telephone
        type_partenaire
    }

    class Camping {
        id_camping
        nom
        adresse
        email
        telephone
    }

    class HistForfait {
        id_hist_forfait
        type_forfait
        prix
        date_achat
        date_expiration
        seances_restantes
    }

    class Cours {
        id_cours
        date_cours
        heure_debut
        niveau
        nb_inscrits
        statut
        capacite_max
    }

    class HistCours {
        id_hist_cours
        date_cours
        heure_debut
        niveau
        nb_inscrits
        statut
        capacite_max
    }

    class Location {
        id_location
        date_debut
        date_fin_prevue
        date_retour
        prix_base
        supplements
    }

    class Panne {
        id_panne
        date_panne
        date_reparation
        cout_reparation
        description
    }

    class HistPanne {
        id_hist_panne
        date_panne
        date_reparation
        cout_reparation
        description
    }

    class Stock {
        id_stock
        type_materiel
        quantite
    }

    class HistStock {
        id_hist_stock
        type_materiel
        quantite
    }

    class Paiement {
        id_paiement
        date_paiement
        montant
        type_paiement
    }

    Client "1" -- "0..*" Forfait: possède
    Client "1" -- "0..*" Location: effectue
    Personnel "1" -- "0..*" Cours: anime
    Materiel "1" -- "0..*" Location: est loué dans
    Forfait "1" -- "0..*" Cours: utilisé pour
    Personnel "1" -- "0..*" Location: supervise
    Materiel "1" -- "0..*" Panne: peut tomber en panne
    Materiel "1" -- "0..*" HistPanne: peut tomber en panne
    Materiel "0..*" -- "1" Stock: est stocké dans
    Materiel "0..*" -- "1" HistStock: est stocké dans
    HistCours "1" - "0..*" HistForfait: utilisé pour
    Personnel "1" - "0..*" HistCours : anime
    HistForfait "1" -- "0..*" Client: possède
    Partenaire "1" -- "1..*" Forfait: vend
    HistPartenaire "1" -- "1..*" HistForfait: vend
    Camping "1" -- "1..*" Client: accueille
    Materiel "1" - "1" Cours: est utilisé pour
    Paiement "1" -- "1..*" Forfait: payé pour
    Saison "1..*" -- "2..*" Personnel: embauche
    Saison "1" -- "0..*" Cours: a lieu pendant
    Saison "1" -- "0..*" Location: a lieu pendant
    Saison "1" -- "0..*" Panne: a lieu pendant
    Saison "1" -- "0..*" HistCours: a lieu pendant
    Saison "1" -- "0..*" HistLocation: a lieu pendant
    HistSaison "1..*" -- "2..*" Personnel: embauche
    HistSaison "1" -- "0..*" Cours: a lieu pendant
    HistSaison "1" -- "0..*" Location: a lieu pendant
    HistSaison "1" -- "0..*" Panne: a lieu pendant
    HistSaison "1" -- "0..*" HistCours: a lieu pendant
    HistSaison "1" -- "0..*" HistLocation: a lieu pendant

@enduml
