@startuml
    class Personnel {
        id_personnel
        nom
        prenom
        type_employe
        email
        telephone
        diplomes
        permis_bateau
    }

    class GarçonDePlage extends Personnel {
        id_garcon
        type_employe
        diplomes
        permis_bateau
    }

    class Moniteur extends Personnel {
        id_moniteur
        type_employe
        diplomes
        permis_bateau
    }

    class Proprietaire extends Personnel {
        id_proprietaire
        type_employe
        diplomes
        permis_bateau
    }

    class Client {
        id_client
        nom
        prenom
        email
        telephone
        piece_identite
    }

    class Materiel {
        id_materiel
        type_materiel
        caracteristiques
        etat
        date_acquisition
        numero_serie
    }

    class Forfait {
        id_forfait
        type_forfait
        prix
        date_achat
        date_expiration
        seances_restantes
        verifCamping()
    }

    class Partenaire {
        id_partenaire
        nom
        adresse
        email
        telephone
        type_partenaire
    }

    class Camping {
        id_camping
        nom
        adresse
        email
        telephone
    }

    class HistForfait {
        id_hist_forfait
        type_forfait
        prix
        date_achat
        date_expiration
        seances_restantes
    }

    class Cours {
        id_cours
        date_cours
        heure_debut
        niveau
        nb_inscrits
        statut
        capacite_max
    }

    class HistCours {
        id_hist_cours
        date_cours
        heure_debut
        niveau
        nb_inscrits
        statut
        capacite_max
    }

    class Location {
        id_location
        date_debut
        date_fin_prevue
        date_retour
        prix_base
        supplements
    }

    class Panne {
        id_panne
        date_panne
        date_reparation
        cout_reparation
        description
    }

    class HistPanne {
        id_hist_panne
        date_panne
        date_reparation
        cout_reparation
        description
    }

    class Stock {
        id_stock
        type_materiel
        quantite
    }

    class HistStock {
        id_hist_stock
        type_materiel
        quantite
    }

    Client "1" -- "0..*" Forfait: possède
    Client "1" -- "0..*" Location: effectue
    Personnel "1" -- "0..*" Cours: anime
    Materiel "1" -- "0..*" Location: est loué dans
    Forfait "1" -- "0..*" Cours: utilisé pour
    Personnel "1" -- "0..*" Location: supervise
    Materiel "1" -- "0..*" Panne: peut tomber en panne
    Materiel "1" -- "0..*" HistPanne: peut tomber en panne
    Materiel "0..*" -- "1" Stock: est stocké dans
    Materiel "0..*" -- "1" HistStock: est stocké dans
    HistCours "1" - "0..*" HistForfait: utilisé pour
    Personnel "1" - "0..*" HistCours : anime
    HistForfait "1" -- "0..*" Client: possède
    Partenaire "1" -- "1..*" Forfait: vend
    Camping "1" -- "1..*" Client: accueille

@enduml
