@startuml
    title État d'une panne

    [*] --> EnPanne
    EnPanne --> Rebut: mettreAuRebut()
    EnPanne --> EnReparation: envoyerEnReparation()
    EnReparation --> Repare: reparer()
    EnReparation --> Rebut: mettreAuRebut()
    Repare --> [*]
    Rebut --> [*]
@enduml
