@startuml
    title État d'une panne

    [*] --> Signalee
    Signalee --> Rebut: mettreAuRebut()
    Signalee --> Reparation: envoyerEnReparation()
    Reparation --> Repare: reparer()
    Reparation --> Rebut: mettreAuRebut()
    Repare --> [*]
    Rebut --> [*]
@enduml
