@startuml
actor "Moniteur" as M
actor "Propriétaire" as P
participant "SYSTEME" as App
participant "Base de donnees" as DB

alt Création de compte Moniteur
    alt Par le Propriétaire
        P -> App : Créer un compte Moniteur
        activate P
    else Par un Moniteur
        M -> App : Créer un compte Moniteur
        activate M
    end

    App -> DB : Vérifier droits de création
    activate DB
    DB --> App : Droits de création confirmés
    deactivate DB

    App -> DB : Enregistrer nouveau compte Moniteur
    activate DB
    DB --> App : Compte créé
    deactivate DB

    alt Par le Propriétaire
        App --> P : Confirmation de création de compte
        deactivate P
    else Par un Moniteur
        App --> M : Confirmation de création de compte
        deactivate M
    end
end

alt Création de compte Garçon de plage
    alt Par le Propriétaire
        P -> App : Créer un compte Garçon de plage
        activate P
    else Par un Moniteur
        M -> App : Créer un compte Garçon de plage
        activate M
    end

    App -> DB : Vérifier droits de création
    activate DB
    DB --> App : Droits de création confirmés
    deactivate DB

    App -> DB : Enregistrer nouveau compte Garçon de plage
    activate DB
    DB --> App : Compte créé
    deactivate DB

    alt Par le Propriétaire
        App --> P : Confirmation de création de compte
        deactivate P
    else Par un Moniteur
        App --> M : Confirmation de création de compte
        deactivate M
    end
end

@enduml
