@startuml
actor ":Personnel" as P
actor ":Gestionnaire du système" as A
participant ":Système" as App
participant ":Base de donnees" as DB

title Création de compte et connexion

== Création de compte ==

A -> App : Créer un compte
activate A
activate App
App -> DB : enregistrerNouveauCompte()
activate DB
DB --> App
deactivate DB
App --> A : Confirmation de création de compte
deactivate App
deactivate A

== Connexion ==
P -> App : Se connecter
activate P
activate App

App -> DB : verifierInformationsConnexion()
activate DB
DB --> App : informationsVerifiees
deactivate DB

App --> P : Connexion réussie
deactivate P
deactivate App
@enduml
