@startuml
actor ":Client" as C
actor ":Moniteur" as M
actor ":Propriétaire" as P
actor "Gestionnaire du système" as A
participant ":SYSTEME" as App
participant ":Base de donnees" as DB
participant ":Matériel" as Mat
participant ":Cours" as Cour
participant ":Forfait" as Forf
participant ":Camping" as Camp
participant ":Paiement" as Pay

title Inscription à un cours

alt Inscription par le Moniteur
    M -> App : Inscrire un client à un cours (niveau, forfait choisi)
    activate M
    activate App
else Inscription par le Propriétaire
    P -> App : Inscrire un client à un cours (niveau, forfait choisi)
    activate P
end

activate App

App -> DB : demanderListeCoursDisponibles()
activate DB
DB --> App : coursDisponibles
deactivate DB

alt Inscription par le Moniteur
    App -> M : Afficher les cours disponibles
    M -> App : Sélectionner un cours (date, horaire)
else Inscription par le Propriétaire
    App -> P : Afficher les cours disponibles
    P -> App : Sélectionner un cours (date, horaire)
end

App -> Mat : verifierDisponibiliteMoniteurEtMateriel()
activate Mat
Mat -> DB : verifierStatutMateriel()
activate DB
DB --> Mat : statutMateriel
deactivate DB
Mat --> DB : verifierStatutMoniteur()
activate DB
DB --> Mat : statutMoniteur
deactivate DB
Mat --> App : disponibiliteMoniteurEtMateriel
deactivate Mat

App -> Forf : calculerPrixForfait()
activate Forf

Forf -> Camp : verifierSiCampingPartenaire()
activate Camp
Camp --> Forf : pourcentageRemise
deactivate Camp
Forf -> Forf : appliquerRemise()

Forf --> App : montantForfait
deactivate Forf

App -> Pay : initialiserPaiement()
activate Pay
Pay --> C : Demander la saisie des informations de paiement
activate C
C --> Pay : Saisir les informations de paiement
deactivate C
Pay --> App : validationPaiement
deactivate Pay

alt Inscription par le Moniteur
    App -> M : Paiement validé
else Inscription par le Propriétaire
    App -> P : Paiement validé
end

App -> Mat : enregistrerReservationMateriel()
activate Mat
DB -> Mat : reserverMateriel()
activate DB
Mat --> DB : confirmationReservationMateriel
deactivate DB
Mat --> App : confirmationEnregistrementReservationMateriel
deactivate Mat

alt Inscription par le Moniteur
    App -> M : Notifier le moniteur (détails du cours)
else Inscription par le Propriétaire
    App -> P : Notifier le propriétaire (détails du cours)
end

App -> P : Envoyer rapport de l'inscription
activate P
P --> App : Accusé de réception
deactivate P

alt Inscription par le Moniteur
    App --> M : Confirmation d'inscription (détails cours, remise, reçu)
    deactivate M
else Inscription par le Propriétaire
    App --> P : Confirmation d'inscription (détails cours, remise, reçu)
    deactivate App
    deactivate P
end
@enduml
